// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: payment/v1/payment.proto

// Payment service contract (P2). Booking is the only caller: it is the saga
// orchestrator, and this is the one synchronous service-to-service hop in the
// system (ARCHITECTURE.md §4.1).

package paymentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChargeStatus mirrors the domain state machine. PENDING is not a transient
// implementation detail: it is the durable record that a charge was started,
// written before the provider is called so an in-flight charge survives a
// crash (FR-4.5). A caller that sees PENDING has an unknown outcome, not a
// failed one.
type ChargeStatus int32

const (
	ChargeStatus_CHARGE_STATUS_UNSPECIFIED ChargeStatus = 0
	ChargeStatus_CHARGE_STATUS_PENDING     ChargeStatus = 1
	ChargeStatus_CHARGE_STATUS_SUCCEEDED   ChargeStatus = 2
	ChargeStatus_CHARGE_STATUS_DECLINED    ChargeStatus = 3
	ChargeStatus_CHARGE_STATUS_FAILED      ChargeStatus = 4
)

// Enum value maps for ChargeStatus.
var (
	ChargeStatus_name = map[int32]string{
		0: "CHARGE_STATUS_UNSPECIFIED",
		1: "CHARGE_STATUS_PENDING",
		2: "CHARGE_STATUS_SUCCEEDED",
		3: "CHARGE_STATUS_DECLINED",
		4: "CHARGE_STATUS_FAILED",
	}
	ChargeStatus_value = map[string]int32{
		"CHARGE_STATUS_UNSPECIFIED": 0,
		"CHARGE_STATUS_PENDING":     1,
		"CHARGE_STATUS_SUCCEEDED":   2,
		"CHARGE_STATUS_DECLINED":    3,
		"CHARGE_STATUS_FAILED":      4,
	}
)

func (x ChargeStatus) Enum() *ChargeStatus {
	p := new(ChargeStatus)
	*p = x
	return p
}

func (x ChargeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChargeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_v1_payment_proto_enumTypes[0].Descriptor()
}

func (ChargeStatus) Type() protoreflect.EnumType {
	return &file_payment_v1_payment_proto_enumTypes[0]
}

func (x ChargeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChargeStatus.Descriptor instead.
func (ChargeStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

type RefundStatus int32

const (
	RefundStatus_REFUND_STATUS_UNSPECIFIED RefundStatus = 0
	RefundStatus_REFUND_STATUS_PENDING     RefundStatus = 1
	RefundStatus_REFUND_STATUS_SUCCEEDED   RefundStatus = 2
	RefundStatus_REFUND_STATUS_FAILED      RefundStatus = 3
)

// Enum value maps for RefundStatus.
var (
	RefundStatus_name = map[int32]string{
		0: "REFUND_STATUS_UNSPECIFIED",
		1: "REFUND_STATUS_PENDING",
		2: "REFUND_STATUS_SUCCEEDED",
		3: "REFUND_STATUS_FAILED",
	}
	RefundStatus_value = map[string]int32{
		"REFUND_STATUS_UNSPECIFIED": 0,
		"REFUND_STATUS_PENDING":     1,
		"REFUND_STATUS_SUCCEEDED":   2,
		"REFUND_STATUS_FAILED":      3,
	}
)

func (x RefundStatus) Enum() *RefundStatus {
	p := new(RefundStatus)
	*p = x
	return p
}

func (x RefundStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefundStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_v1_payment_proto_enumTypes[1].Descriptor()
}

func (RefundStatus) Type() protoreflect.EnumType {
	return &file_payment_v1_payment_proto_enumTypes[1]
}

func (x RefundStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefundStatus.Descriptor instead.
func (RefundStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

type Charge struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReservationId  string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountCents    int64                  `protobuf:"varint,4,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Status         ChargeStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=payment.v1.ChargeStatus" json:"status,omitempty"`
	ProviderRef    string                 `protobuf:"bytes,6,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Populated on DECLINED so the caller can tell the customer why.
	DeclineReason string `protobuf:"bytes,8,opt,name=decline_reason,json=declineReason,proto3" json:"decline_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Charge) Reset() {
	*x = Charge{}
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Charge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Charge) ProtoMessage() {}

func (x *Charge) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Charge.ProtoReflect.Descriptor instead.
func (*Charge) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Charge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Charge) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *Charge) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Charge) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *Charge) GetStatus() ChargeStatus {
	if x != nil {
		return x.Status
	}
	return ChargeStatus_CHARGE_STATUS_UNSPECIFIED
}

func (x *Charge) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

func (x *Charge) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Charge) GetDeclineReason() string {
	if x != nil {
		return x.DeclineReason
	}
	return ""
}

type Refund struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChargeId       string                 `protobuf:"bytes,2,opt,name=charge_id,json=chargeId,proto3" json:"charge_id,omitempty"`
	AmountCents    int64                  `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Status         RefundStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=payment.v1.RefundStatus" json:"status,omitempty"`
	ProviderRef    string                 `protobuf:"bytes,5,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Refund) Reset() {
	*x = Refund{}
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refund) ProtoMessage() {}

func (x *Refund) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refund.ProtoReflect.Descriptor instead.
func (*Refund) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *Refund) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Refund) GetChargeId() string {
	if x != nil {
		return x.ChargeId
	}
	return ""
}

func (x *Refund) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *Refund) GetStatus() RefundStatus {
	if x != nil {
		return x.Status
	}
	return RefundStatus_REFUND_STATUS_UNSPECIFIED
}

func (x *Refund) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

func (x *Refund) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ChargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Money is integer cents everywhere. Never a float (AGENTS.md §5).
	AmountCents int64 `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	// Required (FR-4.3). Replaying a key returns the original charge rather than
	// taking the money twice.
	IdempotencyKey string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChargeRequest) Reset() {
	*x = ChargeRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeRequest) ProtoMessage() {}

func (x *ChargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeRequest.ProtoReflect.Descriptor instead.
func (*ChargeRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *ChargeRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ChargeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChargeRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *ChargeRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ChargeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Charge        *Charge                `protobuf:"bytes,1,opt,name=charge,proto3" json:"charge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChargeResponse) Reset() {
	*x = ChargeResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeResponse) ProtoMessage() {}

func (x *ChargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeResponse.ProtoReflect.Descriptor instead.
func (*ChargeResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *ChargeResponse) GetCharge() *Charge {
	if x != nil {
		return x.Charge
	}
	return nil
}

// GetChargeRequest is what makes the saga's unknown-outcome case converge: the
// reconciliation job asks "what happened to the charge under this key?" and
// gets a definite answer, or PENDING meaning ask again (D8).
type GetChargeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetChargeRequest) Reset() {
	*x = GetChargeRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChargeRequest) ProtoMessage() {}

func (x *GetChargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChargeRequest.ProtoReflect.Descriptor instead.
func (*GetChargeRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetChargeRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetChargeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Charge        *Charge                `protobuf:"bytes,1,opt,name=charge,proto3" json:"charge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChargeResponse) Reset() {
	*x = GetChargeResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChargeResponse) ProtoMessage() {}

func (x *GetChargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChargeResponse.ProtoReflect.Descriptor instead.
func (*GetChargeResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *GetChargeResponse) GetCharge() *Charge {
	if x != nil {
		return x.Charge
	}
	return nil
}

type RefundRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ChargeId    string                 `protobuf:"bytes,1,opt,name=charge_id,json=chargeId,proto3" json:"charge_id,omitempty"`
	AmountCents int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	// Required (FR-4.6). A refund is as dangerous to repeat as a charge.
	IdempotencyKey string `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *RefundRequest) GetChargeId() string {
	if x != nil {
		return x.ChargeId
	}
	return ""
}

func (x *RefundRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *RefundRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type RefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refund        *Refund                `protobuf:"bytes,1,opt,name=refund,proto3" json:"refund,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundResponse) Reset() {
	*x = RefundResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResponse) ProtoMessage() {}

func (x *RefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResponse.ProtoReflect.Descriptor instead.
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *RefundResponse) GetRefund() *Refund {
	if x != nil {
		return x.Refund
	}
	return nil
}

var File_payment_v1_payment_proto protoreflect.FileDescriptor

const file_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x18payment/v1/payment.proto\x12\n" +
	"payment.v1\"\xa0\x02\n" +
	"\x06Charge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12!\n" +
	"\famount_cents\x18\x04 \x01(\x03R\vamountCents\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x18.payment.v1.ChargeStatusR\x06status\x12!\n" +
	"\fprovider_ref\x18\x06 \x01(\tR\vproviderRef\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0edecline_reason\x18\b \x01(\tR\rdeclineReason\"\xd6\x01\n" +
	"\x06Refund\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcharge_id\x18\x02 \x01(\tR\bchargeId\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x03R\vamountCents\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.payment.v1.RefundStatusR\x06status\x12!\n" +
	"\fprovider_ref\x18\x05 \x01(\tR\vproviderRef\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\"\x9b\x01\n" +
	"\rChargeRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x03R\vamountCents\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"<\n" +
	"\x0eChargeResponse\x12*\n" +
	"\x06charge\x18\x01 \x01(\v2\x12.payment.v1.ChargeR\x06charge\";\n" +
	"\x10GetChargeRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\"?\n" +
	"\x11GetChargeResponse\x12*\n" +
	"\x06charge\x18\x01 \x01(\v2\x12.payment.v1.ChargeR\x06charge\"x\n" +
	"\rRefundRequest\x12\x1b\n" +
	"\tcharge_id\x18\x01 \x01(\tR\bchargeId\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"<\n" +
	"\x0eRefundResponse\x12*\n" +
	"\x06refund\x18\x01 \x01(\v2\x12.payment.v1.RefundR\x06refund*\x9b\x01\n" +
	"\fChargeStatus\x12\x1d\n" +
	"\x19CHARGE_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CHARGE_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17CHARGE_STATUS_SUCCEEDED\x10\x02\x12\x1a\n" +
	"\x16CHARGE_STATUS_DECLINED\x10\x03\x12\x18\n" +
	"\x14CHARGE_STATUS_FAILED\x10\x04*\x7f\n" +
	"\fRefundStatus\x12\x1d\n" +
	"\x19REFUND_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REFUND_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17REFUND_STATUS_SUCCEEDED\x10\x02\x12\x18\n" +
	"\x14REFUND_STATUS_FAILED\x10\x032\xdc\x01\n" +
	"\x0ePaymentService\x12?\n" +
	"\x06Charge\x12\x19.payment.v1.ChargeRequest\x1a\x1a.payment.v1.ChargeResponse\x12H\n" +
	"\tGetCharge\x12\x1c.payment.v1.GetChargeRequest\x1a\x1d.payment.v1.GetChargeResponse\x12?\n" +
	"\x06Refund\x12\x19.payment.v1.RefundRequest\x1a\x1a.payment.v1.RefundResponseBKZIgithub.com/lloyd565/concert-ticket-reservation/proto/payment/v1;paymentv1b\x06proto3"

var (
	file_payment_v1_payment_proto_rawDescOnce sync.Once
	file_payment_v1_payment_proto_rawDescData []byte
)

func file_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)))
	})
	return file_payment_v1_payment_proto_rawDescData
}

var file_payment_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_payment_v1_payment_proto_goTypes = []any{
	(ChargeStatus)(0),         // 0: payment.v1.ChargeStatus
	(RefundStatus)(0),         // 1: payment.v1.RefundStatus
	(*Charge)(nil),            // 2: payment.v1.Charge
	(*Refund)(nil),            // 3: payment.v1.Refund
	(*ChargeRequest)(nil),     // 4: payment.v1.ChargeRequest
	(*ChargeResponse)(nil),    // 5: payment.v1.ChargeResponse
	(*GetChargeRequest)(nil),  // 6: payment.v1.GetChargeRequest
	(*GetChargeResponse)(nil), // 7: payment.v1.GetChargeResponse
	(*RefundRequest)(nil),     // 8: payment.v1.RefundRequest
	(*RefundResponse)(nil),    // 9: payment.v1.RefundResponse
}
var file_payment_v1_payment_proto_depIdxs = []int32{
	0, // 0: payment.v1.Charge.status:type_name -> payment.v1.ChargeStatus
	1, // 1: payment.v1.Refund.status:type_name -> payment.v1.RefundStatus
	2, // 2: payment.v1.ChargeResponse.charge:type_name -> payment.v1.Charge
	2, // 3: payment.v1.GetChargeResponse.charge:type_name -> payment.v1.Charge
	3, // 4: payment.v1.RefundResponse.refund:type_name -> payment.v1.Refund
	4, // 5: payment.v1.PaymentService.Charge:input_type -> payment.v1.ChargeRequest
	6, // 6: payment.v1.PaymentService.GetCharge:input_type -> payment.v1.GetChargeRequest
	8, // 7: payment.v1.PaymentService.Refund:input_type -> payment.v1.RefundRequest
	5, // 8: payment.v1.PaymentService.Charge:output_type -> payment.v1.ChargeResponse
	7, // 9: payment.v1.PaymentService.GetCharge:output_type -> payment.v1.GetChargeResponse
	9, // 10: payment.v1.PaymentService.Refund:output_type -> payment.v1.RefundResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_payment_v1_payment_proto_init() }
func file_payment_v1_payment_proto_init() {
	if File_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_payment_v1_payment_proto_depIdxs,
		EnumInfos:         file_payment_v1_payment_proto_enumTypes,
		MessageInfos:      file_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_payment_v1_payment_proto = out.File
	file_payment_v1_payment_proto_goTypes = nil
	file_payment_v1_payment_proto_depIdxs = nil
}
