// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Charge struct {
	ID             uuid.UUID
	ReservationID  uuid.UUID
	UserID         uuid.UUID
	AmountCents    int64
	Status         string
	ProviderRef    *string
	DeclineReason  *string
	IdempotencyKey string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Outbox struct {
	ID           uuid.UUID
	AggregateID  uuid.UUID
	EventType    string
	Payload      []byte
	CreatedAt    time.Time
	PublishedAt  *time.Time
	ClaimedUntil *time.Time
}

type Refund struct {
	ID             uuid.UUID
	ChargeID       uuid.UUID
	AmountCents    int64
	Status         string
	ProviderRef    *string
	IdempotencyKey string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
