// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCharge = `-- name: CreateCharge :exec

INSERT INTO charges (id, reservation_id, user_id, amount_cents, status, idempotency_key, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateChargeParams struct {
	ID             uuid.UUID
	ReservationID  uuid.UUID
	UserID         uuid.UUID
	AmountCents    int64
	Status         string
	IdempotencyKey string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// Hand-written SQL compiled by sqlc into type-safe Go. No ORM by design
// (AGENTS.md §2 rule 4).
//
// The important property in this file is not locking - Payment has no contended
// row - but ordering: the INSERT below happens before any provider call, and
// the settle statements below only ever move a row out of 'pending'.
//
// Written BEFORE the provider is called (FR-4.5). The UNIQUE index on
// idempotency_key is what turns a concurrent double-submit into one charge:
// both callers pass an application-level "have I seen this key" check, and only
// one of them survives this INSERT.
func (q *Queries) CreateCharge(ctx context.Context, arg CreateChargeParams) error {
	_, err := q.db.Exec(ctx, createCharge,
		arg.ID,
		arg.ReservationID,
		arg.UserID,
		arg.AmountCents,
		arg.Status,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createRefund = `-- name: CreateRefund :exec
INSERT INTO refunds (id, charge_id, amount_cents, status, idempotency_key, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateRefundParams struct {
	ID             uuid.UUID
	ChargeID       uuid.UUID
	AmountCents    int64
	Status         string
	IdempotencyKey string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateRefund(ctx context.Context, arg CreateRefundParams) error {
	_, err := q.db.Exec(ctx, createRefund,
		arg.ID,
		arg.ChargeID,
		arg.AmountCents,
		arg.Status,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getChargeByID = `-- name: GetChargeByID :one
SELECT id, reservation_id, user_id, amount_cents, status, provider_ref, decline_reason, idempotency_key, created_at, updated_at
FROM charges
WHERE id = $1
`

func (q *Queries) GetChargeByID(ctx context.Context, id uuid.UUID) (Charge, error) {
	row := q.db.QueryRow(ctx, getChargeByID, id)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.UserID,
		&i.AmountCents,
		&i.Status,
		&i.ProviderRef,
		&i.DeclineReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChargeByIdempotencyKey = `-- name: GetChargeByIdempotencyKey :one
SELECT id, reservation_id, user_id, amount_cents, status, provider_ref, decline_reason, idempotency_key, created_at, updated_at
FROM charges
WHERE idempotency_key = $1
`

// The replay lookup (FR-4.3), and the query Booking's reconciliation job uses
// to resolve an unknown payment outcome (ARCHITECTURE.md §6.3).
func (q *Queries) GetChargeByIdempotencyKey(ctx context.Context, idempotencyKey string) (Charge, error) {
	row := q.db.QueryRow(ctx, getChargeByIdempotencyKey, idempotencyKey)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.UserID,
		&i.AmountCents,
		&i.Status,
		&i.ProviderRef,
		&i.DeclineReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefundByIdempotencyKey = `-- name: GetRefundByIdempotencyKey :one
SELECT id, charge_id, amount_cents, status, provider_ref, idempotency_key, created_at, updated_at
FROM refunds
WHERE idempotency_key = $1
`

func (q *Queries) GetRefundByIdempotencyKey(ctx context.Context, idempotencyKey string) (Refund, error) {
	row := q.db.QueryRow(ctx, getRefundByIdempotencyKey, idempotencyKey)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.ChargeID,
		&i.AmountCents,
		&i.Status,
		&i.ProviderRef,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const settleCharge = `-- name: SettleCharge :execrows
UPDATE charges
SET status         = $1,
    provider_ref   = $2,
    decline_reason = $3,
    updated_at     = $4
WHERE id = $5
  AND status = 'pending'
`

type SettleChargeParams struct {
	Status        string
	ProviderRef   *string
	DeclineReason *string
	UpdatedAt     time.Time
	ID            uuid.UUID
}

// status = 'pending' in the WHERE clause is the guard, not decoration: two
// attempts under one key can both get an answer from the provider, and the
// first settled result is the authoritative one. Without this predicate the
// later writer would silently overwrite it - which for a succeeded charge means
// losing the provider reference the refund depends on.
func (q *Queries) SettleCharge(ctx context.Context, arg SettleChargeParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleCharge,
		arg.Status,
		arg.ProviderRef,
		arg.DeclineReason,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const settleRefund = `-- name: SettleRefund :execrows
UPDATE refunds
SET status       = $1,
    provider_ref = $2,
    updated_at   = $3
WHERE id = $4
  AND status = 'pending'
`

type SettleRefundParams struct {
	Status      string
	ProviderRef *string
	UpdatedAt   time.Time
	ID          uuid.UUID
}

// Same guard as SettleCharge, for the same reason.
func (q *Queries) SettleRefund(ctx context.Context, arg SettleRefundParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleRefund,
		arg.Status,
		arg.ProviderRef,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
