// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimOutboxBatch = `-- name: ClaimOutboxBatch :many
WITH batch AS (
    SELECT o.id
    FROM outbox o
    WHERE o.published_at IS NULL
      AND (o.claimed_until IS NULL OR o.claimed_until < now())
    ORDER BY o.created_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
UPDATE outbox
SET claimed_until = now() + make_interval(0, 0, 0, 0, 0, 0, $1::float8)
FROM batch
WHERE outbox.id = batch.id
RETURNING outbox.id, outbox.event_type, outbox.payload, outbox.created_at
`

type ClaimOutboxBatchParams struct {
	LeaseSeconds float64
	BatchSize    int32
}

type ClaimOutboxBatchRow struct {
	ID        uuid.UUID
	EventType string
	Payload   []byte
	CreatedAt time.Time
}

// Leases a batch of unpublished rows to one relay, and commits at once. No lock
// is held while publishing (D4); the lease is what keeps two relays apart, and a
// lapsed one makes the row claimable again. Measured on the database clock, the
// clock that checks it. RETURNING has no order; the caller sorts.
func (q *Queries) ClaimOutboxBatch(ctx context.Context, arg ClaimOutboxBatchParams) ([]ClaimOutboxBatchRow, error) {
	rows, err := q.db.Query(ctx, claimOutboxBatch, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimOutboxBatchRow
	for rows.Next() {
		var i ClaimOutboxBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCharge = `-- name: CreateCharge :exec

INSERT INTO charges (id, reservation_id, user_id, amount_cents, status, idempotency_key, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateChargeParams struct {
	ID             uuid.UUID
	ReservationID  uuid.UUID
	UserID         uuid.UUID
	AmountCents    int64
	Status         string
	IdempotencyKey string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// Hand-written SQL compiled by sqlc into type-safe Go. No ORM by design
// (AGENTS.md §2 rule 4).
//
// The important property in this file is not locking - Payment has no contended
// row - but ordering: the INSERT below happens before any provider call, and
// the settle statements below only ever move a row out of 'pending'.
//
// Written BEFORE the provider is called (FR-4.5). The UNIQUE index on
// idempotency_key is what turns a concurrent double-submit into one charge:
// both callers pass an application-level "have I seen this key" check, and only
// one of them survives this INSERT.
func (q *Queries) CreateCharge(ctx context.Context, arg CreateChargeParams) error {
	_, err := q.db.Exec(ctx, createCharge,
		arg.ID,
		arg.ReservationID,
		arg.UserID,
		arg.AmountCents,
		arg.Status,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createRefund = `-- name: CreateRefund :exec
INSERT INTO refunds (id, charge_id, amount_cents, status, idempotency_key, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateRefundParams struct {
	ID             uuid.UUID
	ChargeID       uuid.UUID
	AmountCents    int64
	Status         string
	IdempotencyKey string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateRefund(ctx context.Context, arg CreateRefundParams) error {
	_, err := q.db.Exec(ctx, createRefund,
		arg.ID,
		arg.ChargeID,
		arg.AmountCents,
		arg.Status,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getChargeByID = `-- name: GetChargeByID :one
SELECT id, reservation_id, user_id, amount_cents, status, provider_ref, decline_reason, idempotency_key, created_at, updated_at
FROM charges
WHERE id = $1
`

func (q *Queries) GetChargeByID(ctx context.Context, id uuid.UUID) (Charge, error) {
	row := q.db.QueryRow(ctx, getChargeByID, id)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.UserID,
		&i.AmountCents,
		&i.Status,
		&i.ProviderRef,
		&i.DeclineReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChargeByIdempotencyKey = `-- name: GetChargeByIdempotencyKey :one
SELECT id, reservation_id, user_id, amount_cents, status, provider_ref, decline_reason, idempotency_key, created_at, updated_at
FROM charges
WHERE idempotency_key = $1
`

// The replay lookup (FR-4.3), and the query Booking's reconciliation job uses
// to resolve an unknown payment outcome (ARCHITECTURE.md §6.3).
func (q *Queries) GetChargeByIdempotencyKey(ctx context.Context, idempotencyKey string) (Charge, error) {
	row := q.db.QueryRow(ctx, getChargeByIdempotencyKey, idempotencyKey)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.UserID,
		&i.AmountCents,
		&i.Status,
		&i.ProviderRef,
		&i.DeclineReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefundByIdempotencyKey = `-- name: GetRefundByIdempotencyKey :one
SELECT id, charge_id, amount_cents, status, provider_ref, idempotency_key, created_at, updated_at
FROM refunds
WHERE idempotency_key = $1
`

func (q *Queries) GetRefundByIdempotencyKey(ctx context.Context, idempotencyKey string) (Refund, error) {
	row := q.db.QueryRow(ctx, getRefundByIdempotencyKey, idempotencyKey)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.ChargeID,
		&i.AmountCents,
		&i.Status,
		&i.ProviderRef,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox
SET published_at = now()
WHERE id = ANY ($1::uuid[])
`

// Runs only for rows the broker has confirmed. A crash before this line means a
// duplicate publish once the lease lapses - never a loss.
func (q *Queries) MarkOutboxPublished(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, ids)
	return err
}

const settleCharge = `-- name: SettleCharge :one
WITH settled AS (
    UPDATE charges
    SET status         = $1,
        provider_ref   = $2,
        decline_reason = $3,
        updated_at     = $4
    WHERE charges.id = $5
      AND charges.status = 'pending'
    RETURNING charges.id
), announced AS (
    INSERT INTO outbox (id, aggregate_id, event_type, payload, created_at)
    SELECT $6::uuid, settled.id, $7::text, $8::jsonb, $4
    FROM settled
)
SELECT count(*) FROM settled
`

type SettleChargeParams struct {
	Status        string
	ProviderRef   *string
	DeclineReason *string
	UpdatedAt     time.Time
	ID            uuid.UUID
	EventID       uuid.UUID
	EventType     string
	Payload       []byte
}

// status = 'pending' in the WHERE clause is the guard, not decoration: two
// attempts under one key can both get an answer from the provider, and the
// first settled result is the authoritative one. Without this predicate the
// later writer would silently overwrite it - which for a succeeded charge means
// losing the provider reference the refund depends on.
//
// P4: the settlement's event is written by the same statement (D9). The outbox
// row is selected FROM the update, so it exists exactly when the update moved a
// row: a losing duplicate settles nothing and announces nothing, and there is no
// moment at which the charge is settled but its event is not yet recorded.
// Returns how many charges were settled: 1, or 0 for the loser.
func (q *Queries) SettleCharge(ctx context.Context, arg SettleChargeParams) (int64, error) {
	row := q.db.QueryRow(ctx, settleCharge,
		arg.Status,
		arg.ProviderRef,
		arg.DeclineReason,
		arg.UpdatedAt,
		arg.ID,
		arg.EventID,
		arg.EventType,
		arg.Payload,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const settleRefund = `-- name: SettleRefund :one
WITH settled AS (
    UPDATE refunds
    SET status       = $1,
        provider_ref = $2,
        updated_at   = $3
    WHERE refunds.id = $4
      AND refunds.status = 'pending'
    RETURNING refunds.id
), announced AS (
    INSERT INTO outbox (id, aggregate_id, event_type, payload, created_at)
    SELECT $5::uuid, settled.id, $6::text, $7::jsonb, $3
    FROM settled
    WHERE $6::text <> ''
)
SELECT count(*) FROM settled
`

type SettleRefundParams struct {
	Status      string
	ProviderRef *string
	UpdatedAt   time.Time
	ID          uuid.UUID
	EventID     uuid.UUID
	EventType   string
	Payload     []byte
}

// Same guard as SettleCharge, for the same reason, and the same single
// statement for the event. A refund that failed announces nothing: @event_type
// is empty and the INSERT selects no row.
func (q *Queries) SettleRefund(ctx context.Context, arg SettleRefundParams) (int64, error) {
	row := q.db.QueryRow(ctx, settleRefund,
		arg.Status,
		arg.ProviderRef,
		arg.UpdatedAt,
		arg.ID,
		arg.EventID,
		arg.EventType,
		arg.Payload,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}
