// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type DeliveryAttempt struct {
	ID             uuid.UUID
	NotificationID uuid.UUID
	AttemptNo      int32
	Status         string
	Error          *string
	AttemptedAt    time.Time
}

type Notification struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Type      string
	Channel   string
	Status    string
	Payload   []byte
	CreatedAt time.Time
}

type ProcessedEvent struct {
	EventID     uuid.UUID
	ProcessedAt time.Time
}
