// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const isEventProcessed = `-- name: IsEventProcessed :one

SELECT EXISTS (SELECT 1 FROM processed_events WHERE event_id = $1)
`

// Hand-written SQL compiled by sqlc into type-safe Go. No ORM by design
// (AGENTS.md §2 rule 4).
//
// The property that matters in this file is that "this event has been handled"
// and "this email was sent" are recorded by one statement, so they can never
// disagree (see MarkNotificationSent).
//
// The first question asked of every message (D10). Delivery is at-least-once, so
// a yes here is normal, and means: acknowledge and do nothing.
func (q *Queries) IsEventProcessed(ctx context.Context, eventID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isEventProcessed, eventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE notifications
SET status = 'failed'
WHERE id = $1
  AND status = 'pending'
`

// Out of attempts; the message goes to the dead-letter queue. The event is NOT
// recorded as processed: replaying it from the DLQ once delivery works again
// must send the email.
func (q *Queries) MarkNotificationFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, id)
	return err
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
WITH attempt AS (
    INSERT INTO delivery_attempts (id, notification_id, attempt_no, status)
    VALUES ($1, $2, $3, 'sent')
), sent AS (
    UPDATE notifications
    SET status = 'sent'
    WHERE id = $2
    RETURNING id
)
INSERT INTO processed_events (event_id)
SELECT id FROM sent
ON CONFLICT (event_id) DO NOTHING
`

type MarkNotificationSentParams struct {
	AttemptID      uuid.UUID
	NotificationID uuid.UUID
	AttemptNo      int32
}

// The attempt, the status and the processed_events row in one statement.
//
// Written as separate steps, a crash between "sent" and "processed" would let a
// redelivery send the email again; a crash the other way round would mark an
// event handled whose email never went out. One statement has no in-between.
func (q *Queries) MarkNotificationSent(ctx context.Context, arg MarkNotificationSentParams) error {
	_, err := q.db.Exec(ctx, markNotificationSent, arg.AttemptID, arg.NotificationID, arg.AttemptNo)
	return err
}

const recordFailedAttempt = `-- name: RecordFailedAttempt :exec
INSERT INTO delivery_attempts (id, notification_id, attempt_no, status, error)
VALUES ($1, $2, $3, 'failed', $4)
`

type RecordFailedAttemptParams struct {
	ID             uuid.UUID
	NotificationID uuid.UUID
	AttemptNo      int32
	Error          *string
}

func (q *Queries) RecordFailedAttempt(ctx context.Context, arg RecordFailedAttemptParams) error {
	_, err := q.db.Exec(ctx, recordFailedAttempt,
		arg.ID,
		arg.NotificationID,
		arg.AttemptNo,
		arg.Error,
	)
	return err
}

const startNotification = `-- name: StartNotification :one
WITH created AS (
    INSERT INTO notifications (id, user_id, type, channel, status, payload)
    VALUES ($1, $2, $3, $4, 'pending', $5)
    ON CONFLICT (id) DO NOTHING
)
SELECT count(*) FROM delivery_attempts WHERE notification_id = $1
`

type StartNotificationParams struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	Type    string
	Channel string
	Payload []byte
}

// Records the notification about to be attempted, and returns how many attempts
// it has already had.
//
// ON CONFLICT DO NOTHING because a redelivered event - the consumer died
// mid-retry, or the message was replayed from the dead-letter queue - must resume
// its notification, not start a second one. The attempt count carries over with
// it, so a crash loop cannot retry a message forever.
func (q *Queries) StartNotification(ctx context.Context, arg StartNotificationParams) (int64, error) {
	row := q.db.QueryRow(ctx, startNotification,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Channel,
		arg.Payload,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}
