// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminExists = `-- name: AdminExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE role = 'admin')
`

// The guard for the startup admin bootstrap. EXISTS rather than COUNT: the
// question is "is there at least one", and EXISTS stops at the first row.
func (q *Queries) AdminExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, adminExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec

INSERT INTO users (id, email, password_hash, role, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    time.Time
}

// Hand-written SQL compiled by sqlc into type-safe Go. No ORM (AGENTS.md §2
// rule 4). Nothing here contends for a hot row, so nothing here locks: unlike
// Booking, Auth has no shared mutable resource to race for.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, revoked_at
FROM refresh_tokens
WHERE token_hash = $1
`

type GetRefreshTokenRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	RevokedAt *time.Time
}

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash []byte) (GetRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE refresh_tokens
SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
RETURNING id
`

// The WHERE clause is what makes logout idempotent and rotation safe: only a
// live token is revoked, so a replayed logout matches no row and reports
// revoked=false rather than re-stamping a revocation time.
func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeRefreshToken, tokenHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const revokeUserRefreshTokens = `-- name: RevokeUserRefreshTokens :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

// Used when a rotated token is replayed: the replay is evidence the token
// leaked, so every live session for that user is cut.
func (q *Queries) RevokeUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserRefreshTokens, userID)
	return err
}
