// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Event struct {
	ID        uuid.UUID
	Name      string
	StartsAt  time.Time
	CreatedAt time.Time
}

type Reservation struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	EventID        uuid.UUID
	Status         string
	ExpiresAt      time.Time
	IdempotencyKey string
	CreatedAt      time.Time
}

type ReservationSeat struct {
	ReservationID uuid.UUID
	SeatID        uuid.UUID
	ReleasedAt    *time.Time
}

type Seat struct {
	ID                uuid.UUID
	EventID           uuid.UUID
	Section           string
	Row               string
	Number            string
	Status            string
	HeldByReservation *uuid.UUID
	HeldUntil         *time.Time
	CreatedAt         time.Time
}
