// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Booking struct {
	ID            uuid.UUID
	ReservationID uuid.UUID
	UserID        uuid.UUID
	PaymentID     uuid.UUID
	Status        string
	ConfirmedAt   time.Time
}

type ChargeRecheck struct {
	ReservationID uuid.UUID
	ReleasedAt    time.Time
}

type Event struct {
	ID        uuid.UUID
	Name      string
	StartsAt  time.Time
	CreatedAt time.Time
}

type Reservation struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	EventID             uuid.UUID
	Status              string
	ExpiresAt           time.Time
	IdempotencyKey      string
	CreatedAt           time.Time
	TotalCents          int64
	PaymentPendingSince *time.Time
}

type ReservationSeat struct {
	ReservationID uuid.UUID
	SeatID        uuid.UUID
	ReleasedAt    *time.Time
	ConfirmedAt   *time.Time
}

type Seat struct {
	ID         uuid.UUID
	EventID    uuid.UUID
	Section    string
	Row        string
	Number     string
	Status     string
	CreatedAt  time.Time
	PriceCents int64
}

type Ticket struct {
	ID        uuid.UUID
	BookingID uuid.UUID
	SeatID    uuid.UUID
	QrCode    string
	IssuedAt  time.Time
}
