// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const attachSeatsToReservation = `-- name: AttachSeatsToReservation :exec
INSERT INTO reservation_seats (reservation_id, seat_id)
SELECT $1, unnest($2::uuid[])
`

type AttachSeatsToReservationParams struct {
	ReservationID uuid.UUID
	SeatIds       []uuid.UUID
}

// One round trip for N seats. The partial unique index one_active_claim_per_seat
// rejects this insert if any seat already has a live claim (D13 backstop).
func (q *Queries) AttachSeatsToReservation(ctx context.Context, arg AttachSeatsToReservationParams) error {
	_, err := q.db.Exec(ctx, attachSeatsToReservation, arg.ReservationID, arg.SeatIds)
	return err
}

const createBooking = `-- name: CreateBooking :exec
INSERT INTO bookings (id, reservation_id, user_id, payment_id, status, confirmed_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateBookingParams struct {
	ID            uuid.UUID
	ReservationID uuid.UUID
	UserID        uuid.UUID
	PaymentID     uuid.UUID
	Status        string
	ConfirmedAt   time.Time
}

// The reservation_id UNIQUE constraint is what makes confirmation idempotent at
// the database level: a retry, or reconciliation racing the live saga, collides
// here instead of issuing a second set of tickets.
func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) error {
	_, err := q.db.Exec(ctx, createBooking,
		arg.ID,
		arg.ReservationID,
		arg.UserID,
		arg.PaymentID,
		arg.Status,
		arg.ConfirmedAt,
	)
	return err
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (id, name, starts_at)
VALUES ($1, $2, $3)
`

type CreateEventParams struct {
	ID       uuid.UUID
	Name     string
	StartsAt time.Time
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent, arg.ID, arg.Name, arg.StartsAt)
	return err
}

const createReservation = `-- name: CreateReservation :exec
INSERT INTO reservations (id, user_id, event_id, status, total_cents, expires_at, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateReservationParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	EventID        uuid.UUID
	Status         string
	TotalCents     int64
	ExpiresAt      time.Time
	IdempotencyKey string
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) error {
	_, err := q.db.Exec(ctx, createReservation,
		arg.ID,
		arg.UserID,
		arg.EventID,
		arg.Status,
		arg.TotalCents,
		arg.ExpiresAt,
		arg.IdempotencyKey,
	)
	return err
}

type CreateSeatsParams struct {
	ID         uuid.UUID
	EventID    uuid.UUID
	Section    string
	Row        string
	Number     string
	PriceCents int64
}

type CreateTicketsParams struct {
	ID        uuid.UUID
	BookingID uuid.UUID
	SeatID    uuid.UUID
	QrCode    string
}

const getBookingByReservation = `-- name: GetBookingByReservation :one
SELECT id, reservation_id, user_id, payment_id, status, confirmed_at
FROM bookings
WHERE reservation_id = $1
`

func (q *Queries) GetBookingByReservation(ctx context.Context, reservationID uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByReservation, reservationID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.UserID,
		&i.PaymentID,
		&i.Status,
		&i.ConfirmedAt,
	)
	return i, err
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT id, user_id, event_id, status, total_cents, expires_at, idempotency_key, created_at, payment_pending_since
FROM reservations
WHERE id = $1
`

type GetReservationByIDRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	EventID             uuid.UUID
	Status              string
	TotalCents          int64
	ExpiresAt           time.Time
	IdempotencyKey      string
	CreatedAt           time.Time
	PaymentPendingSince *time.Time
}

func (q *Queries) GetReservationByID(ctx context.Context, id uuid.UUID) (GetReservationByIDRow, error) {
	row := q.db.QueryRow(ctx, getReservationByID, id)
	var i GetReservationByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.TotalCents,
		&i.ExpiresAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.PaymentPendingSince,
	)
	return i, err
}

const getReservationByIdempotencyKey = `-- name: GetReservationByIdempotencyKey :one
SELECT id, user_id, event_id, status, total_cents, expires_at, idempotency_key, created_at, payment_pending_since
FROM reservations
WHERE idempotency_key = $1
`

type GetReservationByIdempotencyKeyRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	EventID             uuid.UUID
	Status              string
	TotalCents          int64
	ExpiresAt           time.Time
	IdempotencyKey      string
	CreatedAt           time.Time
	PaymentPendingSince *time.Time
}

// Idempotent retries (FR-3.7): the same key returns the first reservation
// rather than claiming a second set of seats.
func (q *Queries) GetReservationByIdempotencyKey(ctx context.Context, idempotencyKey string) (GetReservationByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getReservationByIdempotencyKey, idempotencyKey)
	var i GetReservationByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.TotalCents,
		&i.ExpiresAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.PaymentPendingSince,
	)
	return i, err
}

const getReservationSeatIDs = `-- name: GetReservationSeatIDs :many
SELECT seat_id
FROM reservation_seats
WHERE reservation_id = $1
ORDER BY seat_id
`

func (q *Queries) GetReservationSeatIDs(ctx context.Context, reservationID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getReservationSeatIDs, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var seat_id uuid.UUID
		if err := rows.Scan(&seat_id); err != nil {
			return nil, err
		}
		items = append(items, seat_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsAwaitingReconciliation = `-- name: ListReservationsAwaitingReconciliation :many
SELECT id, user_id, event_id, status, total_cents, expires_at, idempotency_key, created_at, payment_pending_since
FROM reservations
WHERE status = 'pending'
  AND payment_pending_since IS NOT NULL
  AND payment_pending_since <= $1
ORDER BY payment_pending_since
LIMIT $2
`

type ListReservationsAwaitingReconciliationParams struct {
	OlderThan *time.Time
	RowLimit  int32
}

type ListReservationsAwaitingReconciliationRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	EventID             uuid.UUID
	Status              string
	TotalCents          int64
	ExpiresAt           time.Time
	IdempotencyKey      string
	CreatedAt           time.Time
	PaymentPendingSince *time.Time
}

// The reconciliation scan (ARCHITECTURE.md §6.3): reservations whose payment
// outcome has been unknown for longer than the grace period.
//
// Oldest first, so the longest-stuck reservation is resolved first, and limited
// so one sweep cannot stall on a backlog.
func (q *Queries) ListReservationsAwaitingReconciliation(ctx context.Context, arg ListReservationsAwaitingReconciliationParams) ([]ListReservationsAwaitingReconciliationRow, error) {
	rows, err := q.db.Query(ctx, listReservationsAwaitingReconciliation, arg.OlderThan, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservationsAwaitingReconciliationRow
	for rows.Next() {
		var i ListReservationsAwaitingReconciliationRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.Status,
			&i.TotalCents,
			&i.ExpiresAt,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.PaymentPendingSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeatsByEvent = `-- name: ListSeatsByEvent :many
SELECT id, event_id, section, "row", number, status, held_by_reservation, held_until, price_cents
FROM seats
WHERE event_id = $1
ORDER BY section, "row", number
`

type ListSeatsByEventRow struct {
	ID                uuid.UUID
	EventID           uuid.UUID
	Section           string
	Row               string
	Number            string
	Status            string
	HeldByReservation *uuid.UUID
	HeldUntil         *time.Time
	PriceCents        int64
}

func (q *Queries) ListSeatsByEvent(ctx context.Context, eventID uuid.UUID) ([]ListSeatsByEventRow, error) {
	rows, err := q.db.Query(ctx, listSeatsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeatsByEventRow
	for rows.Next() {
		var i ListSeatsByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Section,
			&i.Row,
			&i.Number,
			&i.Status,
			&i.HeldByReservation,
			&i.HeldUntil,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByBooking = `-- name: ListTicketsByBooking :many
SELECT id, booking_id, seat_id, qr_code, issued_at
FROM tickets
WHERE booking_id = $1
ORDER BY seat_id
`

func (q *Queries) ListTicketsByBooking(ctx context.Context, bookingID uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByBooking, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.SeatID,
			&i.QrCode,
			&i.IssuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReservationForUpdate = `-- name: LockReservationForUpdate :one

SELECT id, user_id, event_id, status, total_cents, expires_at, idempotency_key, created_at, payment_pending_since
FROM reservations
WHERE id = $1
FOR UPDATE
`

type LockReservationForUpdateRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	EventID             uuid.UUID
	Status              string
	TotalCents          int64
	ExpiresAt           time.Time
	IdempotencyKey      string
	CreatedAt           time.Time
	PaymentPendingSince *time.Time
}

// ---------------------------------------------------------------------------
// P2: the reservation saga.
//
// Every statement below runs inside a transaction opened by usecase. The
// ordering discipline is P0's, for P0's reason: the reservation row is locked
// before the seats it owns, on every path, so two concurrent saga steps queue
// instead of forming a waiting cycle.
// ---------------------------------------------------------------------------
//
// Takes the reservation write lock and re-reads its state under it.
//
// Re-reading is the point. Between the payment call and this transaction the
// sweeper may have expired the reservation, or a concurrent retry may have
// confirmed it. The status read here is what the decision is made on; the
// status the caller remembered from before the network hop is stale by
// definition.
func (q *Queries) LockReservationForUpdate(ctx context.Context, id uuid.UUID) (LockReservationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, lockReservationForUpdate, id)
	var i LockReservationForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.TotalCents,
		&i.ExpiresAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.PaymentPendingSince,
	)
	return i, err
}

const lockSeatsByReservation = `-- name: LockSeatsByReservation :many
SELECT s.id, s.event_id, s.section, s."row", s.number, s.status, s.held_by_reservation, s.held_until, s.price_cents
FROM seats s
JOIN reservation_seats rs ON rs.seat_id = s.id
WHERE rs.reservation_id = $1
  AND rs.released_at IS NULL
ORDER BY s.id
FOR UPDATE OF s
`

type LockSeatsByReservationRow struct {
	ID                uuid.UUID
	EventID           uuid.UUID
	Section           string
	Row               string
	Number            string
	Status            string
	HeldByReservation *uuid.UUID
	HeldUntil         *time.Time
	PriceCents        int64
}

// Locks every seat this reservation claims, in seat-ID order (D5). Same
// ordering rule as the hold path, so a confirm, a release and a hold all walk
// contended seat rows in the same sequence and no cycle can form between them.
func (q *Queries) LockSeatsByReservation(ctx context.Context, reservationID uuid.UUID) ([]LockSeatsByReservationRow, error) {
	rows, err := q.db.Query(ctx, lockSeatsByReservation, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockSeatsByReservationRow
	for rows.Next() {
		var i LockSeatsByReservationRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Section,
			&i.Row,
			&i.Number,
			&i.Status,
			&i.HeldByReservation,
			&i.HeldUntil,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSeatsForUpdate = `-- name: LockSeatsForUpdate :many

SELECT id, event_id, section, "row", number, status, held_by_reservation, held_until, price_cents
FROM seats
WHERE event_id = $1
  AND id = ANY ($2::uuid[])
ORDER BY id
FOR UPDATE
`

type LockSeatsForUpdateParams struct {
	EventID uuid.UUID
	SeatIds []uuid.UUID
}

type LockSeatsForUpdateRow struct {
	ID                uuid.UUID
	EventID           uuid.UUID
	Section           string
	Row               string
	Number            string
	Status            string
	HeldByReservation *uuid.UUID
	HeldUntil         *time.Time
	PriceCents        int64
}

// Every query here is hand-written SQL compiled by sqlc into type-safe Go.
// There is no ORM by design (AGENTS.md §2 rule 4): the locking semantics below
// are the correctness core of this service and must be readable as SQL.
//
// THE locking query. This is where the double-booking race is closed.
//
// FOR UPDATE takes a row-level write lock on every matched seat and holds it
// until this transaction commits or rolls back. A concurrent transaction
// running this same query against any of these rows blocks here rather than
// reading a stale 'available' - which is precisely the check-then-act window
// that would otherwise let two requests both believe a seat is free.
//
// ORDER BY id makes the lock acquisition order deterministic (D5). Postgres
// applies the row-locking step above the sort, so rows are locked in id order.
// Every transaction in the system therefore walks contended rows in the same
// sequence and a waiting cycle - a deadlock - cannot form.
func (q *Queries) LockSeatsForUpdate(ctx context.Context, arg LockSeatsForUpdateParams) ([]LockSeatsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, lockSeatsForUpdate, arg.EventID, arg.SeatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockSeatsForUpdateRow
	for rows.Next() {
		var i LockSeatsForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Section,
			&i.Row,
			&i.Number,
			&i.Status,
			&i.HeldByReservation,
			&i.HeldUntil,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentPending = `-- name: MarkPaymentPending :execrows
UPDATE reservations
SET payment_pending_since = now()
WHERE id = $1
  AND status = 'pending'
  AND payment_pending_since IS NULL
`

// Hands the reservation to the reconciliation job (D8). Until this is cleared,
// neither the sweeper nor anything else may release these seats: a charge may
// exist for them and nobody yet knows its outcome.
//
// Idempotent by construction. The first unknown outcome is the one that
// matters, so a repeat leaves the original timestamp alone rather than pushing
// the reconciliation grace period further into the future.
func (q *Queries) MarkPaymentPending(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markPaymentPending, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSeatsBooked = `-- name: MarkSeatsBooked :execrows
UPDATE seats
SET status              = 'booked',
    held_by_reservation = NULL,
    held_until          = NULL
WHERE held_by_reservation = $1
  AND status = 'held'
`

// held -> booked. The hold metadata is cleared because a booked seat is claimed
// permanently rather than until a deadline, and the seats_hold_metadata_consistent
// constraint requires exactly that. status = 'held' is a tripwire: the caller
// compares the row count against the seats it locked, so a seat that moved
// underneath the transaction surfaces as an error, not a partial booking.
func (q *Queries) MarkSeatsBooked(ctx context.Context, reservationID *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markSeatsBooked, reservationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSeatsHeld = `-- name: MarkSeatsHeld :execrows
UPDATE seats
SET status              = 'held',
    held_by_reservation = $1,
    held_until          = $2
WHERE id = ANY ($3::uuid[])
  AND status = 'available'
`

type MarkSeatsHeldParams struct {
	ReservationID *uuid.UUID
	HeldUntil     *time.Time
	SeatIds       []uuid.UUID
}

// The 'act' half of the check-then-act pair. Safe only because the caller is
// inside the transaction that already locked these rows above. The redundant
// status = 'available' predicate is a tripwire: the caller compares the
// affected row count against the number of seats requested, so if the lock
// were ever missing the mismatch surfaces as an error instead of a silent
// partial hold.
func (q *Queries) MarkSeatsHeld(ctx context.Context, arg MarkSeatsHeldParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSeatsHeld, arg.ReservationID, arg.HeldUntil, arg.SeatIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseBookedSeats = `-- name: ReleaseBookedSeats :execrows
WITH released AS (
    UPDATE reservation_seats rs
    SET released_at = now()
    WHERE rs.reservation_id = $1
      AND rs.released_at IS NULL
    RETURNING rs.seat_id
)
UPDATE seats s
SET status              = 'available',
    held_by_reservation = NULL,
    held_until          = NULL
FROM released r
WHERE s.id = r.seat_id
  AND s.status = 'booked'
`

// booked -> available, for a refund. Kept separate from ReleaseReservationSeats
// because the state it moves from is different, and one statement accepting
// either would happily release a seat from a state nobody intended.
func (q *Queries) ReleaseBookedSeats(ctx context.Context, reservationID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, releaseBookedSeats, reservationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseExpiredHolds = `-- name: ReleaseExpiredHolds :execrows
WITH expired AS (
    UPDATE reservations
    SET status = 'expired'
    WHERE status = 'pending'
      AND expires_at <= now()
      AND payment_pending_since IS NULL
    RETURNING id
), released AS (
    UPDATE reservation_seats rs
    SET released_at = now()
    FROM expired e
    WHERE rs.reservation_id = e.id
      AND rs.released_at IS NULL
    RETURNING rs.seat_id
)
UPDATE seats s
SET status              = 'available',
    held_by_reservation = NULL,
    held_until          = NULL
FROM released r
WHERE s.id = r.seat_id
  AND s.status = 'held'
`

// The P0 expiry mechanism (ARCHITECTURE.md §5.2). One statement, so the three
// writes commit together: a reservation can never be marked expired while its
// seats stay held, or vice versa.
//
// Chained CTEs run in a single snapshot: expire the pending reservations whose
// checkout window closed, stamp their claims released (which frees the D13
// index for the next holder), then return exactly those seats to available.
//
// payment_pending_since IS NULL is the D8 guard added in P2, and it is not
// optional. A reservation whose payment outcome is unknown may already have
// been charged; releasing its seats here would sell a seat the customer has
// paid for - the exact mistake D8 forbids, reached through the sweeper rather
// than through the saga. Those rows belong to the reconciliation job alone.
func (q *Queries) ReleaseExpiredHolds(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, releaseExpiredHolds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseReservationSeats = `-- name: ReleaseReservationSeats :execrows
WITH released AS (
    UPDATE reservation_seats rs
    SET released_at = now()
    WHERE rs.reservation_id = $1
      AND rs.released_at IS NULL
    RETURNING rs.seat_id
)
UPDATE seats s
SET status              = 'available',
    held_by_reservation = NULL,
    held_until          = NULL
FROM released r
WHERE s.id = r.seat_id
  AND s.status = 'held'
`

// held -> available, with the claim stamped released so the D13 partial unique
// index frees up for the next holder. One statement, so a claim can never be
// stamped released while its seat stays held.
func (q *Queries) ReleaseReservationSeats(ctx context.Context, reservationID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, releaseReservationSeats, reservationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBookingStatus = `-- name: SetBookingStatus :execrows
UPDATE bookings
SET status = $1
WHERE id = $2
  AND status = $3
`

type SetBookingStatusParams struct {
	NewStatus     string
	ID            uuid.UUID
	CurrentStatus string
}

func (q *Queries) SetBookingStatus(ctx context.Context, arg SetBookingStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBookingStatus, arg.NewStatus, arg.ID, arg.CurrentStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setReservationStatus = `-- name: SetReservationStatus :execrows
UPDATE reservations
SET status = $1,
    -- Reaching a terminal state settles any payment doubt by definition.
    payment_pending_since = NULL
WHERE id = $2
  AND status = $3
`

type SetReservationStatusParams struct {
	NewStatus     string
	ID            uuid.UUID
	CurrentStatus string
}

// @current_status is the guard. Transitions are one-way (FR-5.1), and naming the state
// being left means a concurrent writer that already moved the row cannot be
// silently overwritten: the row count comes back zero and the caller knows it
// lost the race.
func (q *Queries) SetReservationStatus(ctx context.Context, arg SetReservationStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setReservationStatus, arg.NewStatus, arg.ID, arg.CurrentStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
