// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const attachSeatsToReservation = `-- name: AttachSeatsToReservation :exec
INSERT INTO reservation_seats (reservation_id, seat_id)
SELECT $1, unnest($2::uuid[])
`

type AttachSeatsToReservationParams struct {
	ReservationID uuid.UUID
	SeatIds       []uuid.UUID
}

// Records which seats this reservation is for. One round trip for N seats.
//
// These rows are not the claim on the seat - the Redis key is - so this cannot
// trip the D13 index and does not try to. It exists because confirmation has to
// know which seats to book, and Redis cannot answer that: its keys map seat to
// reservation, never the reverse.
func (q *Queries) AttachSeatsToReservation(ctx context.Context, arg AttachSeatsToReservationParams) error {
	_, err := q.db.Exec(ctx, attachSeatsToReservation, arg.ReservationID, arg.SeatIds)
	return err
}

const claimOutboxBatch = `-- name: ClaimOutboxBatch :many
WITH batch AS (
    SELECT o.id
    FROM outbox o
    WHERE o.published_at IS NULL
      AND (o.claimed_until IS NULL OR o.claimed_until < now())
    ORDER BY o.created_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
UPDATE outbox
SET claimed_until = now() + make_interval(0, 0, 0, 0, 0, 0, $1::float8)
FROM batch
WHERE outbox.id = batch.id
RETURNING outbox.id, outbox.event_type, outbox.payload, outbox.created_at
`

type ClaimOutboxBatchParams struct {
	LeaseSeconds float64
	BatchSize    int32
}

type ClaimOutboxBatchRow struct {
	ID        uuid.UUID
	EventType string
	Payload   []byte
	CreatedAt time.Time
}

// Leases a batch of unpublished rows to one relay, and commits at once.
//
// No lock is held while publishing: the relay calls RabbitMQ after this
// statement returns, and a transaction may not span that call (D4). SKIP LOCKED
// only keeps two replicas' claim statements from queueing behind each other; it
// is the lease that keeps them from publishing the same row. A lapsed lease -
// the relay died, or the broker never confirmed - makes the row claimable again.
//
// The lease is measured on the database clock, the same clock that checks it, so
// skew between replicas cannot shorten one. It is built with make_interval
// because sqlc mis-rewrites a named parameter multiplied by an interval literal.
// RETURNING has no order; the caller sorts by created_at.
func (q *Queries) ClaimOutboxBatch(ctx context.Context, arg ClaimOutboxBatchParams) ([]ClaimOutboxBatchRow, error) {
	rows, err := q.db.Query(ctx, claimOutboxBatch, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimOutboxBatchRow
	for rows.Next() {
		var i ClaimOutboxBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearChargeRecheck = `-- name: ClearChargeRecheck :exec
DELETE FROM charge_rechecks
WHERE reservation_id = $1
`

func (q *Queries) ClearChargeRecheck(ctx context.Context, reservationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearChargeRecheck, reservationID)
	return err
}

const createBooking = `-- name: CreateBooking :exec
INSERT INTO bookings (id, reservation_id, user_id, payment_id, status, confirmed_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateBookingParams struct {
	ID            uuid.UUID
	ReservationID uuid.UUID
	UserID        uuid.UUID
	PaymentID     uuid.UUID
	Status        string
	ConfirmedAt   time.Time
}

// The reservation_id UNIQUE constraint is what makes confirmation idempotent at
// the database level: a retry, or reconciliation racing the live saga, collides
// here instead of issuing a second set of tickets.
func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) error {
	_, err := q.db.Exec(ctx, createBooking,
		arg.ID,
		arg.ReservationID,
		arg.UserID,
		arg.PaymentID,
		arg.Status,
		arg.ConfirmedAt,
	)
	return err
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (id, name, starts_at)
VALUES ($1, $2, $3)
`

type CreateEventParams struct {
	ID       uuid.UUID
	Name     string
	StartsAt time.Time
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent, arg.ID, arg.Name, arg.StartsAt)
	return err
}

const createReservation = `-- name: CreateReservation :exec
INSERT INTO reservations (id, user_id, event_id, status, total_cents, expires_at, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateReservationParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	EventID        uuid.UUID
	Status         string
	TotalCents     int64
	ExpiresAt      time.Time
	IdempotencyKey string
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) error {
	_, err := q.db.Exec(ctx, createReservation,
		arg.ID,
		arg.UserID,
		arg.EventID,
		arg.Status,
		arg.TotalCents,
		arg.ExpiresAt,
		arg.IdempotencyKey,
	)
	return err
}

type CreateSeatsParams struct {
	ID         uuid.UUID
	EventID    uuid.UUID
	Section    string
	Row        string
	Number     string
	PriceCents int64
}

type CreateTicketsParams struct {
	ID        uuid.UUID
	BookingID uuid.UUID
	SeatID    uuid.UUID
	QrCode    string
}

const expireLapsedReservations = `-- name: ExpireLapsedReservations :many
WITH lapsed AS (
    SELECT r.id
    FROM reservations r
    WHERE r.status = 'pending'
      AND r.payment_pending_since IS NULL
      AND r.expires_at <= now()
    ORDER BY r.expires_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE reservations
SET status = 'expired'
FROM lapsed
WHERE reservations.id = lapsed.id
  AND reservations.status = 'pending'
  AND reservations.payment_pending_since IS NULL
RETURNING reservations.id, reservations.user_id, reservations.event_id, reservations.expires_at
`

type ExpireLapsedReservationsRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	EventID   uuid.UUID
	ExpiresAt time.Time
}

// Settles reservations whose checkout window closed unpaid, so reservation.expired
// can be written in the transaction that settles them.
//
// This is not the sweeper coming back. It releases no seat and deletes no Redis
// key - the TTL still does that, unaided (§6.2 row 3). It moves a status and
// nothing else.
//
// payment_pending_since IS NULL is D8. A reservation with a charge in doubt
// belongs to reconciliation, and expiring it here would turn a possibly-paid
// customer's reservation into one confirmation refuses. The predicate is checked
// again on the locked row, so a mark written by Pay between the scan and the
// update wins; and Pay's own mark only counts a row still 'pending', so an
// expiry that commits first stops the charge from starting.
func (q *Queries) ExpireLapsedReservations(ctx context.Context, rowLimit int32) ([]ExpireLapsedReservationsRow, error) {
	rows, err := q.db.Query(ctx, expireLapsedReservations, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpireLapsedReservationsRow
	for rows.Next() {
		var i ExpireLapsedReservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingByReservation = `-- name: GetBookingByReservation :one
SELECT id, reservation_id, user_id, payment_id, status, confirmed_at
FROM bookings
WHERE reservation_id = $1
`

func (q *Queries) GetBookingByReservation(ctx context.Context, reservationID uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByReservation, reservationID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.UserID,
		&i.PaymentID,
		&i.Status,
		&i.ConfirmedAt,
	)
	return i, err
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT id, user_id, event_id, status, total_cents, expires_at, idempotency_key, created_at, payment_pending_since
FROM reservations
WHERE id = $1
`

type GetReservationByIDRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	EventID             uuid.UUID
	Status              string
	TotalCents          int64
	ExpiresAt           time.Time
	IdempotencyKey      string
	CreatedAt           time.Time
	PaymentPendingSince *time.Time
}

func (q *Queries) GetReservationByID(ctx context.Context, id uuid.UUID) (GetReservationByIDRow, error) {
	row := q.db.QueryRow(ctx, getReservationByID, id)
	var i GetReservationByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.TotalCents,
		&i.ExpiresAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.PaymentPendingSince,
	)
	return i, err
}

const getReservationByIdempotencyKey = `-- name: GetReservationByIdempotencyKey :one
SELECT id, user_id, event_id, status, total_cents, expires_at, idempotency_key, created_at, payment_pending_since
FROM reservations
WHERE idempotency_key = $1
`

type GetReservationByIdempotencyKeyRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	EventID             uuid.UUID
	Status              string
	TotalCents          int64
	ExpiresAt           time.Time
	IdempotencyKey      string
	CreatedAt           time.Time
	PaymentPendingSince *time.Time
}

// Idempotent retries (FR-3.7): the same key returns the first reservation
// rather than claiming a second set of seats.
func (q *Queries) GetReservationByIdempotencyKey(ctx context.Context, idempotencyKey string) (GetReservationByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getReservationByIdempotencyKey, idempotencyKey)
	var i GetReservationByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.TotalCents,
		&i.ExpiresAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.PaymentPendingSince,
	)
	return i, err
}

const getReservationSeatIDs = `-- name: GetReservationSeatIDs :many
SELECT seat_id
FROM reservation_seats
WHERE reservation_id = $1
ORDER BY seat_id
`

func (q *Queries) GetReservationSeatIDs(ctx context.Context, reservationID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getReservationSeatIDs, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var seat_id uuid.UUID
		if err := rows.Scan(&seat_id); err != nil {
			return nil, err
		}
		items = append(items, seat_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeatsForEvent = `-- name: GetSeatsForEvent :many

SELECT id, event_id, section, "row", number, status, price_cents
FROM seats
WHERE event_id = $1
  AND id = ANY ($2::uuid[])
ORDER BY id
`

type GetSeatsForEventParams struct {
	EventID uuid.UUID
	SeatIds []uuid.UUID
}

type GetSeatsForEventRow struct {
	ID         uuid.UUID
	EventID    uuid.UUID
	Section    string
	Row        string
	Number     string
	Status     string
	PriceCents int64
}

// Every query here is hand-written SQL compiled by sqlc into type-safe Go.
// There is no ORM by design (AGENTS.md §2 rule 4): the locking semantics below
// are the correctness core of this service and must be readable as SQL.
//
// P3 moved the hold out of this file. A hold is a Redis key with a TTL now
// (repository/redis), so nothing here claims a seat; what is left is the
// catalog, the reservation record, and the confirmation - the states that have
// to outlive a Redis restart.
//
// Reads the requested seats' catalog rows: their prices, and whether they have
// already been sold.
//
// No FOR UPDATE, and that is not an oversight. In P0 this query WAS the lock -
// the row lock it took is what closed the check-then-act race. In P3 the lock is
// the Redis SET NX the caller has already won before reaching here, so this is
// a read: do these seats exist, what do they cost, and is one of them booked?
//
// The caller runs it AFTER taking the Redis claim, never before. Confirmation
// commits the booked row and only then deletes the Redis key, so a claim won
// after that delete is guaranteed to see 'booked' here. Reading first would
// reopen exactly the window that ordering closes.
func (q *Queries) GetSeatsForEvent(ctx context.Context, arg GetSeatsForEventParams) ([]GetSeatsForEventRow, error) {
	rows, err := q.db.Query(ctx, getSeatsForEvent, arg.EventID, arg.SeatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeatsForEventRow
	for rows.Next() {
		var i GetSeatsForEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Section,
			&i.Row,
			&i.Number,
			&i.Status,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec

INSERT INTO outbox (id, aggregate_id, event_type, payload, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertOutboxEventParams struct {
	ID          uuid.UUID
	AggregateID uuid.UUID
	EventType   string
	Payload     []byte
	CreatedAt   time.Time
}

// ---------------------------------------------------------------------------
// P4: the transactional outbox (D9, migration 000005).
// ---------------------------------------------------------------------------
//
// Only ever run inside the transaction of the state change the event describes
// (Repo.Enqueue refuses otherwise). That shared transaction is the whole
// pattern: the event commits with the change or not at all.
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const listReservationsAwaitingChargeRecheck = `-- name: ListReservationsAwaitingChargeRecheck :many
SELECT r.id, r.user_id, r.event_id, r.status, r.total_cents, r.expires_at, r.idempotency_key, r.created_at, r.payment_pending_since
FROM charge_rechecks c
JOIN reservations r ON r.id = c.reservation_id
WHERE c.released_at <= $1
ORDER BY c.released_at
LIMIT $2
`

type ListReservationsAwaitingChargeRecheckParams struct {
	OlderThan time.Time
	RowLimit  int32
}

type ListReservationsAwaitingChargeRecheckRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	EventID             uuid.UUID
	Status              string
	TotalCents          int64
	ExpiresAt           time.Time
	IdempotencyKey      string
	CreatedAt           time.Time
	PaymentPendingSince *time.Time
}

// Released reservations whose release is older than the grace period: long
// enough ago that a charge started before the release has reached Payment, if
// it ever will. Oldest first, and limited, like the reconciliation scan.
func (q *Queries) ListReservationsAwaitingChargeRecheck(ctx context.Context, arg ListReservationsAwaitingChargeRecheckParams) ([]ListReservationsAwaitingChargeRecheckRow, error) {
	rows, err := q.db.Query(ctx, listReservationsAwaitingChargeRecheck, arg.OlderThan, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservationsAwaitingChargeRecheckRow
	for rows.Next() {
		var i ListReservationsAwaitingChargeRecheckRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.Status,
			&i.TotalCents,
			&i.ExpiresAt,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.PaymentPendingSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsAwaitingReconciliation = `-- name: ListReservationsAwaitingReconciliation :many
SELECT id, user_id, event_id, status, total_cents, expires_at, idempotency_key, created_at, payment_pending_since
FROM reservations
WHERE status = 'pending'
  AND payment_pending_since IS NOT NULL
  AND payment_pending_since <= $1
ORDER BY payment_pending_since
LIMIT $2
`

type ListReservationsAwaitingReconciliationParams struct {
	OlderThan *time.Time
	RowLimit  int32
}

type ListReservationsAwaitingReconciliationRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	EventID             uuid.UUID
	Status              string
	TotalCents          int64
	ExpiresAt           time.Time
	IdempotencyKey      string
	CreatedAt           time.Time
	PaymentPendingSince *time.Time
}

// The reconciliation scan (ARCHITECTURE.md §6.3): reservations whose payment
// outcome has been unknown for longer than the grace period.
//
// Oldest first, so the longest-stuck reservation is resolved first, and limited
// so one sweep cannot stall on a backlog.
func (q *Queries) ListReservationsAwaitingReconciliation(ctx context.Context, arg ListReservationsAwaitingReconciliationParams) ([]ListReservationsAwaitingReconciliationRow, error) {
	rows, err := q.db.Query(ctx, listReservationsAwaitingReconciliation, arg.OlderThan, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservationsAwaitingReconciliationRow
	for rows.Next() {
		var i ListReservationsAwaitingReconciliationRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.Status,
			&i.TotalCents,
			&i.ExpiresAt,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.PaymentPendingSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeatsByEvent = `-- name: ListSeatsByEvent :many
SELECT id, event_id, section, "row", number, status, price_cents
FROM seats
WHERE event_id = $1
ORDER BY section, "row", number
`

type ListSeatsByEventRow struct {
	ID         uuid.UUID
	EventID    uuid.UUID
	Section    string
	Row        string
	Number     string
	Status     string
	PriceCents int64
}

// The catalog view: available or booked. A seat held by somebody's open
// checkout still reads 'available' here, because that fact lives in Redis.
func (q *Queries) ListSeatsByEvent(ctx context.Context, eventID uuid.UUID) ([]ListSeatsByEventRow, error) {
	rows, err := q.db.Query(ctx, listSeatsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeatsByEventRow
	for rows.Next() {
		var i ListSeatsByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Section,
			&i.Row,
			&i.Number,
			&i.Status,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByBooking = `-- name: ListTicketsByBooking :many
SELECT id, booking_id, seat_id, qr_code, issued_at
FROM tickets
WHERE booking_id = $1
ORDER BY seat_id
`

func (q *Queries) ListTicketsByBooking(ctx context.Context, bookingID uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByBooking, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.SeatID,
			&i.QrCode,
			&i.IssuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReservationForUpdate = `-- name: LockReservationForUpdate :one

SELECT id, user_id, event_id, status, total_cents, expires_at, idempotency_key, created_at, payment_pending_since
FROM reservations
WHERE id = $1
FOR UPDATE
`

type LockReservationForUpdateRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	EventID             uuid.UUID
	Status              string
	TotalCents          int64
	ExpiresAt           time.Time
	IdempotencyKey      string
	CreatedAt           time.Time
	PaymentPendingSince *time.Time
}

// ---------------------------------------------------------------------------
// P2: the reservation saga.
//
// Every statement below runs inside a transaction opened by usecase. The
// ordering discipline is P0's, for P0's reason: the reservation row is locked
// before the seats it owns, on every path, so two concurrent saga steps queue
// instead of forming a waiting cycle.
// ---------------------------------------------------------------------------
//
// Takes the reservation write lock and re-reads its state under it.
//
// Re-reading is the point. Between the payment call and this transaction the
// Redis hold may have expired and the seats gone to somebody else, or a
// concurrent retry may have confirmed it. The status read here is what the
// decision is made on; the status the caller remembered from before the network
// hop is stale by definition.
func (q *Queries) LockReservationForUpdate(ctx context.Context, id uuid.UUID) (LockReservationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, lockReservationForUpdate, id)
	var i LockReservationForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.TotalCents,
		&i.ExpiresAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.PaymentPendingSince,
	)
	return i, err
}

const lockSeatsByReservation = `-- name: LockSeatsByReservation :many
SELECT s.id, s.event_id, s.section, s."row", s.number, s.status, s.price_cents
FROM seats s
JOIN reservation_seats rs ON rs.seat_id = s.id
WHERE rs.reservation_id = $1
  AND rs.released_at IS NULL
ORDER BY s.id
FOR UPDATE OF s
`

type LockSeatsByReservationRow struct {
	ID         uuid.UUID
	EventID    uuid.UUID
	Section    string
	Row        string
	Number     string
	Status     string
	PriceCents int64
}

// THE locking query in P3. Confirmation is where a transient Redis hold becomes
// a permanent Postgres fact, so it is where Postgres has to be certain, and FOR
// UPDATE is what makes it so: two reservations that both believe they hold this
// seat - because a hold expired and was re-taken while a charge was in flight -
// queue here instead of both reading 'available'.
//
// ORDER BY s.id (D5), so the confirm and refund paths walk contended rows in the
// same sequence and no waiting cycle can form between them.
func (q *Queries) LockSeatsByReservation(ctx context.Context, reservationID uuid.UUID) ([]LockSeatsByReservationRow, error) {
	rows, err := q.db.Query(ctx, lockSeatsByReservation, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockSeatsByReservationRow
	for rows.Next() {
		var i LockSeatsByReservationRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Section,
			&i.Row,
			&i.Number,
			&i.Status,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox
SET published_at = now()
WHERE id = ANY ($1::uuid[])
`

// Runs only for rows the broker has confirmed. A crash before this line means
// the row is published again once its lease lapses: a duplicate, which every
// consumer is required to survive (D10) - never a loss.
func (q *Queries) MarkOutboxPublished(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, ids)
	return err
}

const markPaymentPending = `-- name: MarkPaymentPending :execrows
UPDATE reservations
SET payment_pending_since = COALESCE(payment_pending_since, now())
WHERE id = $1
  AND status = 'pending'
`

// Hands the reservation to the reconciliation job (D8). Until this is cleared,
// nothing else may release these seats: a charge may exist for them and nobody
// yet knows its outcome.
//
// In P0 this column also told the sweeper to keep its hands off. There is no
// sweeper now, so this is only half of D8 - the caller must also push the Redis
// TTL out, or the hold simply expires and the seats go back on sale under a
// charge that may have succeeded. See Saga.LeavePendingForReconciliation.
//
// It is also the fence in front of every charge. The row count says whether the
// reservation was still pending at this instant, and the saga calls Payment only
// if it was. Once a release commits no new charge can start for it, so any
// charge a release missed was already under way - which is what bounds how long
// reconciliation waits before rechecking (migration 000004).
//
// Idempotent by construction. The first mark is the one that matters, so a
// repeat keeps the original timestamp rather than pushing the reconciliation
// grace period further into the future - and still counts the row, because the
// fence is about the status, not about who marked first.
func (q *Queries) MarkPaymentPending(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markPaymentPending, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSeatsBooked = `-- name: MarkSeatsBooked :execrows
WITH confirmed AS (
    UPDATE reservation_seats rs
    SET confirmed_at = now()
    WHERE rs.reservation_id = $1
      AND rs.released_at IS NULL
    RETURNING rs.seat_id
)
UPDATE seats s
SET status = 'booked'
FROM confirmed c
WHERE s.id = c.seat_id
  AND s.status = 'available'
`

// available -> booked, with the claim stamped confirmed at the same instant, in
// one statement so the seat row and the D13 index can never disagree about who
// owns the seat.
//
// status = 'available' is the tripwire the caller counts against the seats it
// locked above: if another reservation booked this seat first, the count comes
// back short and confirmation fails rather than silently overwriting a sale.
func (q *Queries) MarkSeatsBooked(ctx context.Context, reservationID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markSeatsBooked, reservationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const queueChargeRecheck = `-- name: QueueChargeRecheck :exec
INSERT INTO charge_rechecks (reservation_id)
VALUES ($1)
ON CONFLICT (reservation_id) DO NOTHING
`

// Queues a reservation just released on "no charge" evidence for one more look
// (migration 000004). Runs in the release's transaction: a release that commits
// without it is exactly the orphan the table exists to prevent.
func (q *Queries) QueueChargeRecheck(ctx context.Context, reservationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, queueChargeRecheck, reservationID)
	return err
}

const releaseBookedSeats = `-- name: ReleaseBookedSeats :execrows
WITH released AS (
    UPDATE reservation_seats rs
    SET released_at = now()
    WHERE rs.reservation_id = $1
      AND rs.released_at IS NULL
    RETURNING rs.seat_id
)
UPDATE seats s
SET status = 'available'
FROM released r
WHERE s.id = r.seat_id
  AND s.status = 'booked'
`

// booked -> available, for a refund, with the claim stamped released so the D13
// index frees up for the next buyer. One statement, so a claim can never be
// stamped released while its seat stays booked.
func (q *Queries) ReleaseBookedSeats(ctx context.Context, reservationID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, releaseBookedSeats, reservationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseReservationClaims = `-- name: ReleaseReservationClaims :execrows
UPDATE reservation_seats
SET released_at = now()
WHERE reservation_id = $1
  AND released_at IS NULL
  AND confirmed_at IS NULL
`

// Settles an unconfirmed reservation's claim rows without touching a seat -
// because in P3 an unconfirmed claim never owned the seat in the first place;
// the Redis key did, and the caller deletes that separately.
//
// Bookkeeping, not compensation. It is what makes "this reservation is over"
// legible in the database rather than only in Redis's absence.
func (q *Queries) ReleaseReservationClaims(ctx context.Context, reservationID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, releaseReservationClaims, reservationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBookingStatus = `-- name: SetBookingStatus :execrows
UPDATE bookings
SET status = $1
WHERE id = $2
  AND status = $3
`

type SetBookingStatusParams struct {
	NewStatus     string
	ID            uuid.UUID
	CurrentStatus string
}

func (q *Queries) SetBookingStatus(ctx context.Context, arg SetBookingStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBookingStatus, arg.NewStatus, arg.ID, arg.CurrentStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setReservationStatus = `-- name: SetReservationStatus :execrows
UPDATE reservations
SET status = $1,
    -- Reaching a terminal state settles any payment doubt by definition.
    payment_pending_since = NULL
WHERE id = $2
  AND status = $3
`

type SetReservationStatusParams struct {
	NewStatus     string
	ID            uuid.UUID
	CurrentStatus string
}

// @current_status is the guard. Transitions are one-way (FR-5.1), and naming the state
// being left means a concurrent writer that already moved the row cannot be
// silently overwritten: the row count comes back zero and the caller knows it
// lost the race.
func (q *Queries) SetReservationStatus(ctx context.Context, arg SetReservationStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setReservationStatus, arg.NewStatus, arg.ID, arg.CurrentStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
