// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const attachSeatsToReservation = `-- name: AttachSeatsToReservation :exec
INSERT INTO reservation_seats (reservation_id, seat_id)
SELECT $1, unnest($2::uuid[])
`

type AttachSeatsToReservationParams struct {
	ReservationID uuid.UUID
	SeatIds       []uuid.UUID
}

// One round trip for N seats. The partial unique index one_active_claim_per_seat
// rejects this insert if any seat already has a live claim (D13 backstop).
func (q *Queries) AttachSeatsToReservation(ctx context.Context, arg AttachSeatsToReservationParams) error {
	_, err := q.db.Exec(ctx, attachSeatsToReservation, arg.ReservationID, arg.SeatIds)
	return err
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (id, name, starts_at)
VALUES ($1, $2, $3)
`

type CreateEventParams struct {
	ID       uuid.UUID
	Name     string
	StartsAt time.Time
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent, arg.ID, arg.Name, arg.StartsAt)
	return err
}

const createReservation = `-- name: CreateReservation :exec
INSERT INTO reservations (id, user_id, event_id, status, expires_at, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateReservationParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	EventID        uuid.UUID
	Status         string
	ExpiresAt      time.Time
	IdempotencyKey string
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) error {
	_, err := q.db.Exec(ctx, createReservation,
		arg.ID,
		arg.UserID,
		arg.EventID,
		arg.Status,
		arg.ExpiresAt,
		arg.IdempotencyKey,
	)
	return err
}

type CreateSeatsParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
	Section string
	Row     string
	Number  string
}

const getReservationByIdempotencyKey = `-- name: GetReservationByIdempotencyKey :one
SELECT id, user_id, event_id, status, expires_at, idempotency_key, created_at
FROM reservations
WHERE idempotency_key = $1
`

// Idempotent retries (FR-3.7): the same key returns the first reservation
// rather than claiming a second set of seats.
func (q *Queries) GetReservationByIdempotencyKey(ctx context.Context, idempotencyKey string) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByIdempotencyKey, idempotencyKey)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.ExpiresAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getReservationSeatIDs = `-- name: GetReservationSeatIDs :many
SELECT seat_id
FROM reservation_seats
WHERE reservation_id = $1
ORDER BY seat_id
`

func (q *Queries) GetReservationSeatIDs(ctx context.Context, reservationID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getReservationSeatIDs, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var seat_id uuid.UUID
		if err := rows.Scan(&seat_id); err != nil {
			return nil, err
		}
		items = append(items, seat_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeatsByEvent = `-- name: ListSeatsByEvent :many
SELECT id, event_id, section, "row", number, status, held_by_reservation, held_until
FROM seats
WHERE event_id = $1
ORDER BY section, "row", number
`

type ListSeatsByEventRow struct {
	ID                uuid.UUID
	EventID           uuid.UUID
	Section           string
	Row               string
	Number            string
	Status            string
	HeldByReservation *uuid.UUID
	HeldUntil         *time.Time
}

func (q *Queries) ListSeatsByEvent(ctx context.Context, eventID uuid.UUID) ([]ListSeatsByEventRow, error) {
	rows, err := q.db.Query(ctx, listSeatsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeatsByEventRow
	for rows.Next() {
		var i ListSeatsByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Section,
			&i.Row,
			&i.Number,
			&i.Status,
			&i.HeldByReservation,
			&i.HeldUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSeatsForUpdate = `-- name: LockSeatsForUpdate :many

SELECT id, event_id, section, "row", number, status, held_by_reservation, held_until
FROM seats
WHERE event_id = $1
  AND id = ANY ($2::uuid[])
ORDER BY id
FOR UPDATE
`

type LockSeatsForUpdateParams struct {
	EventID uuid.UUID
	SeatIds []uuid.UUID
}

type LockSeatsForUpdateRow struct {
	ID                uuid.UUID
	EventID           uuid.UUID
	Section           string
	Row               string
	Number            string
	Status            string
	HeldByReservation *uuid.UUID
	HeldUntil         *time.Time
}

// Every query here is hand-written SQL compiled by sqlc into type-safe Go.
// There is no ORM by design (AGENTS.md §2 rule 4): the locking semantics below
// are the correctness core of this service and must be readable as SQL.
//
// THE locking query. This is where the double-booking race is closed.
//
// FOR UPDATE takes a row-level write lock on every matched seat and holds it
// until this transaction commits or rolls back. A concurrent transaction
// running this same query against any of these rows blocks here rather than
// reading a stale 'available' - which is precisely the check-then-act window
// that would otherwise let two requests both believe a seat is free.
//
// ORDER BY id makes the lock acquisition order deterministic (D5). Postgres
// applies the row-locking step above the sort, so rows are locked in id order.
// Every transaction in the system therefore walks contended rows in the same
// sequence and a waiting cycle - a deadlock - cannot form.
func (q *Queries) LockSeatsForUpdate(ctx context.Context, arg LockSeatsForUpdateParams) ([]LockSeatsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, lockSeatsForUpdate, arg.EventID, arg.SeatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockSeatsForUpdateRow
	for rows.Next() {
		var i LockSeatsForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Section,
			&i.Row,
			&i.Number,
			&i.Status,
			&i.HeldByReservation,
			&i.HeldUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSeatsHeld = `-- name: MarkSeatsHeld :execrows
UPDATE seats
SET status              = 'held',
    held_by_reservation = $1,
    held_until          = $2
WHERE id = ANY ($3::uuid[])
  AND status = 'available'
`

type MarkSeatsHeldParams struct {
	ReservationID *uuid.UUID
	HeldUntil     *time.Time
	SeatIds       []uuid.UUID
}

// The 'act' half of the check-then-act pair. Safe only because the caller is
// inside the transaction that already locked these rows above. The redundant
// status = 'available' predicate is a tripwire: the caller compares the
// affected row count against the number of seats requested, so if the lock
// were ever missing the mismatch surfaces as an error instead of a silent
// partial hold.
func (q *Queries) MarkSeatsHeld(ctx context.Context, arg MarkSeatsHeldParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSeatsHeld, arg.ReservationID, arg.HeldUntil, arg.SeatIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseExpiredHolds = `-- name: ReleaseExpiredHolds :execrows
WITH expired AS (
    UPDATE reservations
    SET status = 'expired'
    WHERE status = 'pending'
      AND expires_at <= now()
    RETURNING id
), released AS (
    UPDATE reservation_seats rs
    SET released_at = now()
    FROM expired e
    WHERE rs.reservation_id = e.id
      AND rs.released_at IS NULL
    RETURNING rs.seat_id
)
UPDATE seats s
SET status              = 'available',
    held_by_reservation = NULL,
    held_until          = NULL
FROM released r
WHERE s.id = r.seat_id
  AND s.status = 'held'
`

// The P0 expiry mechanism (ARCHITECTURE.md §5.2). One statement, so the three
// writes commit together: a reservation can never be marked expired while its
// seats stay held, or vice versa.
//
// Chained CTEs run in a single snapshot: expire the pending reservations whose
// checkout window closed, stamp their claims released (which frees the D13
// index for the next holder), then return exactly those seats to available.
func (q *Queries) ReleaseExpiredHolds(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, releaseExpiredHolds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
