// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: booking/v1/booking.proto

// Booking service contract. P2 adds the saga entry point: holding seats and
// paying for them are two operations, not one, because the attendee gets a
// 10-minute checkout window between them (PRD §4.1 steps 4-5) and because the
// hold transaction must commit before Payment is called (D4).

package bookingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BookingService_SeedEvent_FullMethodName      = "/booking.v1.BookingService/SeedEvent"
	BookingService_HoldSeats_FullMethodName      = "/booking.v1.BookingService/HoldSeats"
	BookingService_PayReservation_FullMethodName = "/booking.v1.BookingService/PayReservation"
)

// BookingServiceClient is the client API for BookingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookingServiceClient interface {
	SeedEvent(ctx context.Context, in *SeedEventRequest, opts ...grpc.CallOption) (*SeedEventResponse, error)
	HoldSeats(ctx context.Context, in *HoldSeatsRequest, opts ...grpc.CallOption) (*HoldSeatsResponse, error)
	PayReservation(ctx context.Context, in *PayReservationRequest, opts ...grpc.CallOption) (*PayReservationResponse, error)
}

type bookingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingServiceClient(cc grpc.ClientConnInterface) BookingServiceClient {
	return &bookingServiceClient{cc}
}

func (c *bookingServiceClient) SeedEvent(ctx context.Context, in *SeedEventRequest, opts ...grpc.CallOption) (*SeedEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeedEventResponse)
	err := c.cc.Invoke(ctx, BookingService_SeedEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) HoldSeats(ctx context.Context, in *HoldSeatsRequest, opts ...grpc.CallOption) (*HoldSeatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HoldSeatsResponse)
	err := c.cc.Invoke(ctx, BookingService_HoldSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) PayReservation(ctx context.Context, in *PayReservationRequest, opts ...grpc.CallOption) (*PayReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayReservationResponse)
	err := c.cc.Invoke(ctx, BookingService_PayReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingServiceServer is the server API for BookingService service.
// All implementations must embed UnimplementedBookingServiceServer
// for forward compatibility.
type BookingServiceServer interface {
	SeedEvent(context.Context, *SeedEventRequest) (*SeedEventResponse, error)
	HoldSeats(context.Context, *HoldSeatsRequest) (*HoldSeatsResponse, error)
	PayReservation(context.Context, *PayReservationRequest) (*PayReservationResponse, error)
	mustEmbedUnimplementedBookingServiceServer()
}

// UnimplementedBookingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBookingServiceServer struct{}

func (UnimplementedBookingServiceServer) SeedEvent(context.Context, *SeedEventRequest) (*SeedEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SeedEvent not implemented")
}
func (UnimplementedBookingServiceServer) HoldSeats(context.Context, *HoldSeatsRequest) (*HoldSeatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HoldSeats not implemented")
}
func (UnimplementedBookingServiceServer) PayReservation(context.Context, *PayReservationRequest) (*PayReservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayReservation not implemented")
}
func (UnimplementedBookingServiceServer) mustEmbedUnimplementedBookingServiceServer() {}
func (UnimplementedBookingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBookingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookingServiceServer will
// result in compilation errors.
type UnsafeBookingServiceServer interface {
	mustEmbedUnimplementedBookingServiceServer()
}

func RegisterBookingServiceServer(s grpc.ServiceRegistrar, srv BookingServiceServer) {
	// If the following call pancis, it indicates UnimplementedBookingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BookingService_ServiceDesc, srv)
}

func _BookingService_SeedEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeedEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).SeedEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_SeedEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).SeedEvent(ctx, req.(*SeedEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_HoldSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HoldSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).HoldSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_HoldSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).HoldSeats(ctx, req.(*HoldSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_PayReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).PayReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_PayReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).PayReservation(ctx, req.(*PayReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookingService_ServiceDesc is the grpc.ServiceDesc for BookingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "booking.v1.BookingService",
	HandlerType: (*BookingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SeedEvent",
			Handler:    _BookingService_SeedEvent_Handler,
		},
		{
			MethodName: "HoldSeats",
			Handler:    _BookingService_HoldSeats_Handler,
		},
		{
			MethodName: "PayReservation",
			Handler:    _BookingService_PayReservation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "booking/v1/booking.proto",
}
